/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as api_ from "../api.js";
import type * as http from "../http.js";
import type * as pangeaAuth from "../pangeaAuth.js";
import type * as pangeaAuthActions from "../pangeaAuthActions.js";
import type * as pangeaAuthMutations from "../pangeaAuthMutations.js";
import type * as pangeaAuthQueries from "../pangeaAuthQueries.js";
import type * as pangeaSShare from "../pangeaSShare.js";
import type * as pangeaSShareActions from "../pangeaSShareActions.js";
import type * as pangeaSShareMutations from "../pangeaSShareMutations.js";
import type * as square from "../square.js";
import type * as squareActions from "../squareActions.js";
import type * as squareMutations from "../squareMutations.js";
import type * as squareQueries from "../squareQueries.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  api: typeof api_;
  http: typeof http;
  pangeaAuth: typeof pangeaAuth;
  pangeaAuthActions: typeof pangeaAuthActions;
  pangeaAuthMutations: typeof pangeaAuthMutations;
  pangeaAuthQueries: typeof pangeaAuthQueries;
  pangeaSShare: typeof pangeaSShare;
  pangeaSShareActions: typeof pangeaSShareActions;
  pangeaSShareMutations: typeof pangeaSShareMutations;
  square: typeof square;
  squareActions: typeof squareActions;
  squareMutations: typeof squareMutations;
  squareQueries: typeof squareQueries;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
